"""Repro experiment (2026-06-10): does the honest engine agree with live reality?

Context: live paper trading 05-18→06-10 closed 43 trades at 27.9% WR / −$572,
while the headline 90d backtest claims 65% / $36.47/day. The parity audit showed
the live cohort was generated by a DIFFERENT strategy than the backtest measures:
old wide watchlist + sub-70 "marginal band" entries (median live entry score 62)
+ May-era sizing knobs. This script asks the honest engine to score *that*
strategy over *that* window:

  Run A (--universe may): the 24 symbols live actually traded, threshold 60,
    May knobs (risk 2%, cap 20%, $4.5k, regime mult forced 1.0 — the up-scaling
    layer didn't exist in May). If the engine ALSO bleeds here, engine and
    reality agree and the May strategy/universe was the problem — the simulator
    is usable as a yardstick. If the engine is green, the simulator itself is
    still optimistic beyond the known exit/fill gaps.

  Run B (--universe current): today's pinned 10-name list + current .env knobs
    over the same 23-day window — what the engine claims the post-parity
    strategy would have done while live placed ~1 entry in 5 sessions.

Deliberately does NOT call run_backtest() so data/backtest_results.json (the
GUI's number) is never overwritten by an experiment.
"""
from __future__ import annotations
import argparse, json, logging, os, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

# Run A predates the regime up-scaling layer — neutralize it BEFORE src.config
# loads .env (REGIME_BULL_MULT=1.4 there would inflate May-cohort sizing).
ap = argparse.ArgumentParser()
ap.add_argument("--universe", choices=["may", "current"], required=True)
ap.add_argument("--days", type=int, default=23)  # 05-18 → 06-10
args = ap.parse_args()
if args.universe == "may":
    os.environ["REGIME_BULL_MULT"] = "1.0"

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s | %(message)s")
from src.backtest import BacktestConfig, prefetch_data, _run_live_engine  # noqa: E402
from src.config import settings  # noqa: E402

# Every symbol with a closed live trade in the window (trader.db, 24 names).
MAY_TRADED = [
    "AAPL", "ABNB", "AMZN", "CNC", "CSCO", "DDOG", "DXCM", "FTNT", "GEN",
    "HPE", "HPQ", "INTC", "IWM", "MCHP", "MSFT", "QCOM", "QQQ", "SWKS",
    "TXN", "UBER", "V", "WDC", "XLE", "XLF",
]

if args.universe == "may":
    cfg = BacktestConfig(
        days=args.days, timeframe="HOUR_1",
        threshold=60.0,            # marginal band floor (live median entry score 62)
        tickers=MAY_TRADED,
        account_usd=4500.0,        # May budget
        risk_per_trade=0.02,       # May knob (now 0.05)
        max_position_pct=0.20,     # May knob (now 0.70)
        max_hold_days=7,
        tp_atr_mult=8.0, sl_atr_mult=3.5,
    )
else:
    cfg = BacktestConfig(
        days=args.days, timeframe="HOUR_1",
        threshold=70.0,
        tickers=[],                # → config/watchlist.json (pinned 10)
        account_usd=settings.account_usd,
        risk_per_trade=settings.risk_per_trade,
        max_position_pct=settings.max_position_pct,
        max_hold_days=settings.max_hold_days,
        tp_atr_mult=settings.tp_atr_mult,
        sl_atr_mult=settings.sl_atr_mult,
    )

cache = prefetch_data(cfg)
got = len(cache.get("per_ticker") or {})
if got == 0:
    print(json.dumps({"universe": args.universe, "error": "prefetch returned 0 tickers (OpenD down?)"}))
    sys.exit(1)

result = _run_live_engine(cfg, cache, rich_metrics=True)
m = result["metrics"]
trades = result["trades"]

by_exit: dict[str, int] = {}
for t in trades:
    by_exit[t.get("exit_reason", "?")] = by_exit.get(t.get("exit_reason", "?"), 0) + 1

out = {
    "universe": args.universe,
    "tickers_cached": got,
    "days": args.days,
    "threshold": cfg.threshold,
    "n_trades": m.get("total_trades"),
    "win_rate": m.get("win_rate"),
    "total_pnl": m.get("total_pnl"),
    "pnl_per_day": m.get("pnl_per_day"),
    "max_dd_pct": m.get("max_drawdown_pct"),
    "final_equity": m.get("final_equity"),
    "by_exit": by_exit,
    "metric_keys": sorted(m.keys()),
}
print("REPRO_RESULT " + json.dumps(out))
